// Code generated by protoc-gen-go.
// source: acourse.proto
// DO NOT EDIT!

/*
Package acourse is a generated protocol buffer package.

It is generated from these files:
	acourse.proto

It has these top-level messages:
	GetUserRequest
	GetUserResponse
	GetMeResponse
	ListRequest
	PaymentsResponse
	PaymentIDsRequest
	PaymentUpdatePriceRequest
	CoursesResponse
	UserIDRequest
	CourseIDRequest
	EnrollRequest
	CourseResponse
	Empty
	User
	UserTiny
	Role
	Email
	Course
	CourseSmall
	CourseTiny
	Payment
	EnrollCount
*/
package acourse

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type GetUserRequest struct {
	UserIds []string `protobuf:"bytes,1,rep,name=userIds" json:"userIds,omitempty"`
}

func (m *GetUserRequest) Reset()                    { *m = GetUserRequest{} }
func (m *GetUserRequest) String() string            { return proto.CompactTextString(m) }
func (*GetUserRequest) ProtoMessage()               {}
func (*GetUserRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *GetUserRequest) GetUserIds() []string {
	if m != nil {
		return m.UserIds
	}
	return nil
}

type GetUserResponse struct {
	Users []*User `protobuf:"bytes,1,rep,name=users" json:"users,omitempty"`
}

func (m *GetUserResponse) Reset()                    { *m = GetUserResponse{} }
func (m *GetUserResponse) String() string            { return proto.CompactTextString(m) }
func (*GetUserResponse) ProtoMessage()               {}
func (*GetUserResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *GetUserResponse) GetUsers() []*User {
	if m != nil {
		return m.Users
	}
	return nil
}

type GetMeResponse struct {
	User *User `protobuf:"bytes,1,opt,name=user" json:"user,omitempty"`
	Role *Role `protobuf:"bytes,2,opt,name=role" json:"role,omitempty"`
}

func (m *GetMeResponse) Reset()                    { *m = GetMeResponse{} }
func (m *GetMeResponse) String() string            { return proto.CompactTextString(m) }
func (*GetMeResponse) ProtoMessage()               {}
func (*GetMeResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *GetMeResponse) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *GetMeResponse) GetRole() *Role {
	if m != nil {
		return m.Role
	}
	return nil
}

type ListRequest struct {
	Offset int32 `protobuf:"varint,1,opt,name=offset" json:"offset,omitempty"`
	Limit  int32 `protobuf:"varint,2,opt,name=limit" json:"limit,omitempty"`
}

func (m *ListRequest) Reset()                    { *m = ListRequest{} }
func (m *ListRequest) String() string            { return proto.CompactTextString(m) }
func (*ListRequest) ProtoMessage()               {}
func (*ListRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *ListRequest) GetOffset() int32 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *ListRequest) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

type PaymentsResponse struct {
	Payments []*Payment    `protobuf:"bytes,1,rep,name=payments" json:"payments,omitempty"`
	Users    []*UserTiny   `protobuf:"bytes,2,rep,name=users" json:"users,omitempty"`
	Courses  []*CourseTiny `protobuf:"bytes,3,rep,name=courses" json:"courses,omitempty"`
}

func (m *PaymentsResponse) Reset()                    { *m = PaymentsResponse{} }
func (m *PaymentsResponse) String() string            { return proto.CompactTextString(m) }
func (*PaymentsResponse) ProtoMessage()               {}
func (*PaymentsResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *PaymentsResponse) GetPayments() []*Payment {
	if m != nil {
		return m.Payments
	}
	return nil
}

func (m *PaymentsResponse) GetUsers() []*UserTiny {
	if m != nil {
		return m.Users
	}
	return nil
}

func (m *PaymentsResponse) GetCourses() []*CourseTiny {
	if m != nil {
		return m.Courses
	}
	return nil
}

type PaymentIDsRequest struct {
	PaymentIds []string `protobuf:"bytes,1,rep,name=paymentIds" json:"paymentIds,omitempty"`
}

func (m *PaymentIDsRequest) Reset()                    { *m = PaymentIDsRequest{} }
func (m *PaymentIDsRequest) String() string            { return proto.CompactTextString(m) }
func (*PaymentIDsRequest) ProtoMessage()               {}
func (*PaymentIDsRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *PaymentIDsRequest) GetPaymentIds() []string {
	if m != nil {
		return m.PaymentIds
	}
	return nil
}

type PaymentUpdatePriceRequest struct {
	PaymentId string  `protobuf:"bytes,1,opt,name=paymentId" json:"paymentId,omitempty"`
	Price     float64 `protobuf:"fixed64,2,opt,name=price" json:"price,omitempty"`
}

func (m *PaymentUpdatePriceRequest) Reset()                    { *m = PaymentUpdatePriceRequest{} }
func (m *PaymentUpdatePriceRequest) String() string            { return proto.CompactTextString(m) }
func (*PaymentUpdatePriceRequest) ProtoMessage()               {}
func (*PaymentUpdatePriceRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *PaymentUpdatePriceRequest) GetPaymentId() string {
	if m != nil {
		return m.PaymentId
	}
	return ""
}

func (m *PaymentUpdatePriceRequest) GetPrice() float64 {
	if m != nil {
		return m.Price
	}
	return 0
}

type CoursesResponse struct {
	Courses      []*CourseSmall `protobuf:"bytes,1,rep,name=courses" json:"courses,omitempty"`
	Users        []*UserTiny    `protobuf:"bytes,2,rep,name=users" json:"users,omitempty"`
	EnrollCounts []*EnrollCount `protobuf:"bytes,3,rep,name=enrollCounts" json:"enrollCounts,omitempty"`
}

func (m *CoursesResponse) Reset()                    { *m = CoursesResponse{} }
func (m *CoursesResponse) String() string            { return proto.CompactTextString(m) }
func (*CoursesResponse) ProtoMessage()               {}
func (*CoursesResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *CoursesResponse) GetCourses() []*CourseSmall {
	if m != nil {
		return m.Courses
	}
	return nil
}

func (m *CoursesResponse) GetUsers() []*UserTiny {
	if m != nil {
		return m.Users
	}
	return nil
}

func (m *CoursesResponse) GetEnrollCounts() []*EnrollCount {
	if m != nil {
		return m.EnrollCounts
	}
	return nil
}

type UserIDRequest struct {
	UserId string `protobuf:"bytes,1,opt,name=userId" json:"userId,omitempty"`
}

func (m *UserIDRequest) Reset()                    { *m = UserIDRequest{} }
func (m *UserIDRequest) String() string            { return proto.CompactTextString(m) }
func (*UserIDRequest) ProtoMessage()               {}
func (*UserIDRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *UserIDRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

type CourseIDRequest struct {
	CourseId string `protobuf:"bytes,1,opt,name=courseId" json:"courseId,omitempty"`
}

func (m *CourseIDRequest) Reset()                    { *m = CourseIDRequest{} }
func (m *CourseIDRequest) String() string            { return proto.CompactTextString(m) }
func (*CourseIDRequest) ProtoMessage()               {}
func (*CourseIDRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *CourseIDRequest) GetCourseId() string {
	if m != nil {
		return m.CourseId
	}
	return ""
}

type EnrollRequest struct {
	CourseId string  `protobuf:"bytes,1,opt,name=courseId" json:"courseId,omitempty"`
	Url      string  `protobuf:"bytes,2,opt,name=url" json:"url,omitempty"`
	Code     string  `protobuf:"bytes,3,opt,name=code" json:"code,omitempty"`
	Price    float64 `protobuf:"fixed64,4,opt,name=price" json:"price,omitempty"`
}

func (m *EnrollRequest) Reset()                    { *m = EnrollRequest{} }
func (m *EnrollRequest) String() string            { return proto.CompactTextString(m) }
func (*EnrollRequest) ProtoMessage()               {}
func (*EnrollRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *EnrollRequest) GetCourseId() string {
	if m != nil {
		return m.CourseId
	}
	return ""
}

func (m *EnrollRequest) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *EnrollRequest) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *EnrollRequest) GetPrice() float64 {
	if m != nil {
		return m.Price
	}
	return 0
}

type CourseResponse struct {
	Course   *Course   `protobuf:"bytes,1,opt,name=course" json:"course,omitempty"`
	User     *UserTiny `protobuf:"bytes,2,opt,name=user" json:"user,omitempty"`
	Enrolled bool      `protobuf:"varint,3,opt,name=enrolled" json:"enrolled,omitempty"`
	Owned    bool      `protobuf:"varint,4,opt,name=owned" json:"owned,omitempty"`
	Purchase bool      `protobuf:"varint,5,opt,name=purchase" json:"purchase,omitempty"`
	Attended bool      `protobuf:"varint,6,opt,name=attended" json:"attended,omitempty"`
}

func (m *CourseResponse) Reset()                    { *m = CourseResponse{} }
func (m *CourseResponse) String() string            { return proto.CompactTextString(m) }
func (*CourseResponse) ProtoMessage()               {}
func (*CourseResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func (m *CourseResponse) GetCourse() *Course {
	if m != nil {
		return m.Course
	}
	return nil
}

func (m *CourseResponse) GetUser() *UserTiny {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *CourseResponse) GetEnrolled() bool {
	if m != nil {
		return m.Enrolled
	}
	return false
}

func (m *CourseResponse) GetOwned() bool {
	if m != nil {
		return m.Owned
	}
	return false
}

func (m *CourseResponse) GetPurchase() bool {
	if m != nil {
		return m.Purchase
	}
	return false
}

func (m *CourseResponse) GetAttended() bool {
	if m != nil {
		return m.Attended
	}
	return false
}

type Empty struct {
}

func (m *Empty) Reset()                    { *m = Empty{} }
func (m *Empty) String() string            { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()               {}
func (*Empty) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

type User struct {
	Id       string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Username string `protobuf:"bytes,2,opt,name=username" json:"username,omitempty"`
	Name     string `protobuf:"bytes,3,opt,name=name" json:"name,omitempty"`
	Photo    string `protobuf:"bytes,4,opt,name=photo" json:"photo,omitempty"`
	AboutMe  string `protobuf:"bytes,5,opt,name=aboutMe" json:"aboutMe,omitempty"`
}

func (m *User) Reset()                    { *m = User{} }
func (m *User) String() string            { return proto.CompactTextString(m) }
func (*User) ProtoMessage()               {}
func (*User) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{13} }

func (m *User) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *User) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *User) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *User) GetPhoto() string {
	if m != nil {
		return m.Photo
	}
	return ""
}

func (m *User) GetAboutMe() string {
	if m != nil {
		return m.AboutMe
	}
	return ""
}

type UserTiny struct {
	Id       string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Username string `protobuf:"bytes,2,opt,name=username" json:"username,omitempty"`
	Name     string `protobuf:"bytes,3,opt,name=name" json:"name,omitempty"`
	Photo    string `protobuf:"bytes,4,opt,name=photo" json:"photo,omitempty"`
}

func (m *UserTiny) Reset()                    { *m = UserTiny{} }
func (m *UserTiny) String() string            { return proto.CompactTextString(m) }
func (*UserTiny) ProtoMessage()               {}
func (*UserTiny) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{14} }

func (m *UserTiny) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *UserTiny) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *UserTiny) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UserTiny) GetPhoto() string {
	if m != nil {
		return m.Photo
	}
	return ""
}

type Role struct {
	Admin      bool `protobuf:"varint,1,opt,name=admin" json:"admin,omitempty"`
	Instructor bool `protobuf:"varint,2,opt,name=instructor" json:"instructor,omitempty"`
}

func (m *Role) Reset()                    { *m = Role{} }
func (m *Role) String() string            { return proto.CompactTextString(m) }
func (*Role) ProtoMessage()               {}
func (*Role) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{15} }

func (m *Role) GetAdmin() bool {
	if m != nil {
		return m.Admin
	}
	return false
}

func (m *Role) GetInstructor() bool {
	if m != nil {
		return m.Instructor
	}
	return false
}

type Email struct {
	To      []string `protobuf:"bytes,1,rep,name=to" json:"to,omitempty"`
	Subject string   `protobuf:"bytes,2,opt,name=subject" json:"subject,omitempty"`
	Body    string   `protobuf:"bytes,4,opt,name=body" json:"body,omitempty"`
}

func (m *Email) Reset()                    { *m = Email{} }
func (m *Email) String() string            { return proto.CompactTextString(m) }
func (*Email) ProtoMessage()               {}
func (*Email) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{16} }

func (m *Email) GetTo() []string {
	if m != nil {
		return m.To
	}
	return nil
}

func (m *Email) GetSubject() string {
	if m != nil {
		return m.Subject
	}
	return ""
}

func (m *Email) GetBody() string {
	if m != nil {
		return m.Body
	}
	return ""
}

type Course struct {
	Id               string               `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	CreatedAt        string               `protobuf:"bytes,2,opt,name=createdAt" json:"createdAt,omitempty"`
	UpdatedAt        string               `protobuf:"bytes,3,opt,name=updatedAt" json:"updatedAt,omitempty"`
	Title            string               `protobuf:"bytes,4,opt,name=title" json:"title,omitempty"`
	ShortDescription string               `protobuf:"bytes,5,opt,name=shortDescription" json:"shortDescription,omitempty"`
	Description      string               `protobuf:"bytes,6,opt,name=description" json:"description,omitempty"`
	Photo            string               `protobuf:"bytes,7,opt,name=photo" json:"photo,omitempty"`
	Owner            string               `protobuf:"bytes,8,opt,name=owner" json:"owner,omitempty"`
	Start            string               `protobuf:"bytes,9,opt,name=start" json:"start,omitempty"`
	Url              string               `protobuf:"bytes,10,opt,name=url" json:"url,omitempty"`
	Type             string               `protobuf:"bytes,11,opt,name=type" json:"type,omitempty"`
	Video            string               `protobuf:"bytes,12,opt,name=video" json:"video,omitempty"`
	Price            float64              `protobuf:"fixed64,13,opt,name=price" json:"price,omitempty"`
	DiscountedPrice  float64              `protobuf:"fixed64,14,opt,name=discountedPrice" json:"discountedPrice,omitempty"`
	Options          *Course_Option       `protobuf:"bytes,15,opt,name=options" json:"options,omitempty"`
	Contents         []*Course_Content    `protobuf:"bytes,16,rep,name=contents" json:"contents,omitempty"`
	EnrollDetail     string               `protobuf:"bytes,17,opt,name=enrollDetail" json:"enrollDetail,omitempty"`
	Assignments      []*Course_Assignment `protobuf:"bytes,18,rep,name=assignments" json:"assignments,omitempty"`
}

func (m *Course) Reset()                    { *m = Course{} }
func (m *Course) String() string            { return proto.CompactTextString(m) }
func (*Course) ProtoMessage()               {}
func (*Course) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{17} }

func (m *Course) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Course) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

func (m *Course) GetUpdatedAt() string {
	if m != nil {
		return m.UpdatedAt
	}
	return ""
}

func (m *Course) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Course) GetShortDescription() string {
	if m != nil {
		return m.ShortDescription
	}
	return ""
}

func (m *Course) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Course) GetPhoto() string {
	if m != nil {
		return m.Photo
	}
	return ""
}

func (m *Course) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func (m *Course) GetStart() string {
	if m != nil {
		return m.Start
	}
	return ""
}

func (m *Course) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *Course) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Course) GetVideo() string {
	if m != nil {
		return m.Video
	}
	return ""
}

func (m *Course) GetPrice() float64 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *Course) GetDiscountedPrice() float64 {
	if m != nil {
		return m.DiscountedPrice
	}
	return 0
}

func (m *Course) GetOptions() *Course_Option {
	if m != nil {
		return m.Options
	}
	return nil
}

func (m *Course) GetContents() []*Course_Content {
	if m != nil {
		return m.Contents
	}
	return nil
}

func (m *Course) GetEnrollDetail() string {
	if m != nil {
		return m.EnrollDetail
	}
	return ""
}

func (m *Course) GetAssignments() []*Course_Assignment {
	if m != nil {
		return m.Assignments
	}
	return nil
}

type Course_Content struct {
	Title       string `protobuf:"bytes,1,opt,name=title" json:"title,omitempty"`
	Description string `protobuf:"bytes,2,opt,name=description" json:"description,omitempty"`
	Video       string `protobuf:"bytes,3,opt,name=video" json:"video,omitempty"`
	DownloadURL string `protobuf:"bytes,4,opt,name=downloadURL" json:"downloadURL,omitempty"`
}

func (m *Course_Content) Reset()                    { *m = Course_Content{} }
func (m *Course_Content) String() string            { return proto.CompactTextString(m) }
func (*Course_Content) ProtoMessage()               {}
func (*Course_Content) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{17, 0} }

func (m *Course_Content) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Course_Content) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Course_Content) GetVideo() string {
	if m != nil {
		return m.Video
	}
	return ""
}

func (m *Course_Content) GetDownloadURL() string {
	if m != nil {
		return m.DownloadURL
	}
	return ""
}

type Course_Option struct {
	Public     bool `protobuf:"varint,1,opt,name=public" json:"public,omitempty"`
	Enroll     bool `protobuf:"varint,2,opt,name=enroll" json:"enroll,omitempty"`
	Attend     bool `protobuf:"varint,3,opt,name=attend" json:"attend,omitempty"`
	Assignment bool `protobuf:"varint,4,opt,name=assignment" json:"assignment,omitempty"`
	Discount   bool `protobuf:"varint,5,opt,name=discount" json:"discount,omitempty"`
}

func (m *Course_Option) Reset()                    { *m = Course_Option{} }
func (m *Course_Option) String() string            { return proto.CompactTextString(m) }
func (*Course_Option) ProtoMessage()               {}
func (*Course_Option) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{17, 1} }

func (m *Course_Option) GetPublic() bool {
	if m != nil {
		return m.Public
	}
	return false
}

func (m *Course_Option) GetEnroll() bool {
	if m != nil {
		return m.Enroll
	}
	return false
}

func (m *Course_Option) GetAttend() bool {
	if m != nil {
		return m.Attend
	}
	return false
}

func (m *Course_Option) GetAssignment() bool {
	if m != nil {
		return m.Assignment
	}
	return false
}

func (m *Course_Option) GetDiscount() bool {
	if m != nil {
		return m.Discount
	}
	return false
}

type Course_Assignment struct {
	Title       string `protobuf:"bytes,1,opt,name=title" json:"title,omitempty"`
	Description string `protobuf:"bytes,2,opt,name=description" json:"description,omitempty"`
	Open        bool   `protobuf:"varint,3,opt,name=open" json:"open,omitempty"`
}

func (m *Course_Assignment) Reset()                    { *m = Course_Assignment{} }
func (m *Course_Assignment) String() string            { return proto.CompactTextString(m) }
func (*Course_Assignment) ProtoMessage()               {}
func (*Course_Assignment) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{17, 2} }

func (m *Course_Assignment) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Course_Assignment) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Course_Assignment) GetOpen() bool {
	if m != nil {
		return m.Open
	}
	return false
}

type CourseSmall struct {
	Id               string              `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Title            string              `protobuf:"bytes,4,opt,name=title" json:"title,omitempty"`
	ShortDescription string              `protobuf:"bytes,5,opt,name=shortDescription" json:"shortDescription,omitempty"`
	Photo            string              `protobuf:"bytes,7,opt,name=photo" json:"photo,omitempty"`
	Owner            string              `protobuf:"bytes,8,opt,name=owner" json:"owner,omitempty"`
	Start            string              `protobuf:"bytes,9,opt,name=start" json:"start,omitempty"`
	Url              string              `protobuf:"bytes,10,opt,name=url" json:"url,omitempty"`
	Type             string              `protobuf:"bytes,11,opt,name=type" json:"type,omitempty"`
	Price            float64             `protobuf:"fixed64,13,opt,name=price" json:"price,omitempty"`
	DiscountedPrice  float64             `protobuf:"fixed64,14,opt,name=discountedPrice" json:"discountedPrice,omitempty"`
	Options          *CourseSmall_Option `protobuf:"bytes,15,opt,name=options" json:"options,omitempty"`
}

func (m *CourseSmall) Reset()                    { *m = CourseSmall{} }
func (m *CourseSmall) String() string            { return proto.CompactTextString(m) }
func (*CourseSmall) ProtoMessage()               {}
func (*CourseSmall) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{18} }

func (m *CourseSmall) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *CourseSmall) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *CourseSmall) GetShortDescription() string {
	if m != nil {
		return m.ShortDescription
	}
	return ""
}

func (m *CourseSmall) GetPhoto() string {
	if m != nil {
		return m.Photo
	}
	return ""
}

func (m *CourseSmall) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func (m *CourseSmall) GetStart() string {
	if m != nil {
		return m.Start
	}
	return ""
}

func (m *CourseSmall) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *CourseSmall) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *CourseSmall) GetPrice() float64 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *CourseSmall) GetDiscountedPrice() float64 {
	if m != nil {
		return m.DiscountedPrice
	}
	return 0
}

func (m *CourseSmall) GetOptions() *CourseSmall_Option {
	if m != nil {
		return m.Options
	}
	return nil
}

type CourseSmall_Option struct {
	Discount bool `protobuf:"varint,5,opt,name=discount" json:"discount,omitempty"`
}

func (m *CourseSmall_Option) Reset()                    { *m = CourseSmall_Option{} }
func (m *CourseSmall_Option) String() string            { return proto.CompactTextString(m) }
func (*CourseSmall_Option) ProtoMessage()               {}
func (*CourseSmall_Option) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{18, 0} }

func (m *CourseSmall_Option) GetDiscount() bool {
	if m != nil {
		return m.Discount
	}
	return false
}

type CourseTiny struct {
	Id    string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Title string `protobuf:"bytes,2,opt,name=title" json:"title,omitempty"`
}

func (m *CourseTiny) Reset()                    { *m = CourseTiny{} }
func (m *CourseTiny) String() string            { return proto.CompactTextString(m) }
func (*CourseTiny) ProtoMessage()               {}
func (*CourseTiny) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{19} }

func (m *CourseTiny) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *CourseTiny) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

type Payment struct {
	Id            string  `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	CreatedAt     string  `protobuf:"bytes,2,opt,name=createdAt" json:"createdAt,omitempty"`
	UpdatedAt     string  `protobuf:"bytes,3,opt,name=updatedAt" json:"updatedAt,omitempty"`
	UserId        string  `protobuf:"bytes,4,opt,name=userId" json:"userId,omitempty"`
	CourseId      string  `protobuf:"bytes,5,opt,name=courseId" json:"courseId,omitempty"`
	OriginalPrice float64 `protobuf:"fixed64,6,opt,name=originalPrice" json:"originalPrice,omitempty"`
	Price         float64 `protobuf:"fixed64,7,opt,name=price" json:"price,omitempty"`
	Code          string  `protobuf:"bytes,8,opt,name=code" json:"code,omitempty"`
	Url           string  `protobuf:"bytes,9,opt,name=url" json:"url,omitempty"`
	Status        string  `protobuf:"bytes,10,opt,name=status" json:"status,omitempty"`
	At            string  `protobuf:"bytes,11,opt,name=at" json:"at,omitempty"`
}

func (m *Payment) Reset()                    { *m = Payment{} }
func (m *Payment) String() string            { return proto.CompactTextString(m) }
func (*Payment) ProtoMessage()               {}
func (*Payment) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{20} }

func (m *Payment) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Payment) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

func (m *Payment) GetUpdatedAt() string {
	if m != nil {
		return m.UpdatedAt
	}
	return ""
}

func (m *Payment) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *Payment) GetCourseId() string {
	if m != nil {
		return m.CourseId
	}
	return ""
}

func (m *Payment) GetOriginalPrice() float64 {
	if m != nil {
		return m.OriginalPrice
	}
	return 0
}

func (m *Payment) GetPrice() float64 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *Payment) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *Payment) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *Payment) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *Payment) GetAt() string {
	if m != nil {
		return m.At
	}
	return ""
}

type EnrollCount struct {
	CourseId string `protobuf:"bytes,1,opt,name=courseId" json:"courseId,omitempty"`
	Count    int32  `protobuf:"varint,2,opt,name=count" json:"count,omitempty"`
}

func (m *EnrollCount) Reset()                    { *m = EnrollCount{} }
func (m *EnrollCount) String() string            { return proto.CompactTextString(m) }
func (*EnrollCount) ProtoMessage()               {}
func (*EnrollCount) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{21} }

func (m *EnrollCount) GetCourseId() string {
	if m != nil {
		return m.CourseId
	}
	return ""
}

func (m *EnrollCount) GetCount() int32 {
	if m != nil {
		return m.Count
	}
	return 0
}

func init() {
	proto.RegisterType((*GetUserRequest)(nil), "acourse.GetUserRequest")
	proto.RegisterType((*GetUserResponse)(nil), "acourse.GetUserResponse")
	proto.RegisterType((*GetMeResponse)(nil), "acourse.GetMeResponse")
	proto.RegisterType((*ListRequest)(nil), "acourse.ListRequest")
	proto.RegisterType((*PaymentsResponse)(nil), "acourse.PaymentsResponse")
	proto.RegisterType((*PaymentIDsRequest)(nil), "acourse.PaymentIDsRequest")
	proto.RegisterType((*PaymentUpdatePriceRequest)(nil), "acourse.PaymentUpdatePriceRequest")
	proto.RegisterType((*CoursesResponse)(nil), "acourse.CoursesResponse")
	proto.RegisterType((*UserIDRequest)(nil), "acourse.UserIDRequest")
	proto.RegisterType((*CourseIDRequest)(nil), "acourse.CourseIDRequest")
	proto.RegisterType((*EnrollRequest)(nil), "acourse.EnrollRequest")
	proto.RegisterType((*CourseResponse)(nil), "acourse.CourseResponse")
	proto.RegisterType((*Empty)(nil), "acourse.Empty")
	proto.RegisterType((*User)(nil), "acourse.User")
	proto.RegisterType((*UserTiny)(nil), "acourse.UserTiny")
	proto.RegisterType((*Role)(nil), "acourse.Role")
	proto.RegisterType((*Email)(nil), "acourse.Email")
	proto.RegisterType((*Course)(nil), "acourse.Course")
	proto.RegisterType((*Course_Content)(nil), "acourse.Course.Content")
	proto.RegisterType((*Course_Option)(nil), "acourse.Course.Option")
	proto.RegisterType((*Course_Assignment)(nil), "acourse.Course.Assignment")
	proto.RegisterType((*CourseSmall)(nil), "acourse.CourseSmall")
	proto.RegisterType((*CourseSmall_Option)(nil), "acourse.CourseSmall.Option")
	proto.RegisterType((*CourseTiny)(nil), "acourse.CourseTiny")
	proto.RegisterType((*Payment)(nil), "acourse.Payment")
	proto.RegisterType((*EnrollCount)(nil), "acourse.EnrollCount")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for UserService service

type UserServiceClient interface {
	GetUser(ctx context.Context, in *GetUserRequest, opts ...grpc.CallOption) (*GetUserResponse, error)
	GetMe(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*GetMeResponse, error)
	UpdateMe(ctx context.Context, in *User, opts ...grpc.CallOption) (*Empty, error)
}

type userServiceClient struct {
	cc *grpc.ClientConn
}

func NewUserServiceClient(cc *grpc.ClientConn) UserServiceClient {
	return &userServiceClient{cc}
}

func (c *userServiceClient) GetUser(ctx context.Context, in *GetUserRequest, opts ...grpc.CallOption) (*GetUserResponse, error) {
	out := new(GetUserResponse)
	err := grpc.Invoke(ctx, "/acourse.UserService/GetUser", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) GetMe(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*GetMeResponse, error) {
	out := new(GetMeResponse)
	err := grpc.Invoke(ctx, "/acourse.UserService/GetMe", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) UpdateMe(ctx context.Context, in *User, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := grpc.Invoke(ctx, "/acourse.UserService/UpdateMe", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for UserService service

type UserServiceServer interface {
	GetUser(context.Context, *GetUserRequest) (*GetUserResponse, error)
	GetMe(context.Context, *Empty) (*GetMeResponse, error)
	UpdateMe(context.Context, *User) (*Empty, error)
}

func RegisterUserServiceServer(s *grpc.Server, srv UserServiceServer) {
	s.RegisterService(&_UserService_serviceDesc, srv)
}

func _UserService_GetUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).GetUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/acourse.UserService/GetUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).GetUser(ctx, req.(*GetUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_GetMe_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).GetMe(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/acourse.UserService/GetMe",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).GetMe(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_UpdateMe_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(User)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).UpdateMe(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/acourse.UserService/UpdateMe",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).UpdateMe(ctx, req.(*User))
	}
	return interceptor(ctx, in, info, handler)
}

var _UserService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "acourse.UserService",
	HandlerType: (*UserServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetUser",
			Handler:    _UserService_GetUser_Handler,
		},
		{
			MethodName: "GetMe",
			Handler:    _UserService_GetMe_Handler,
		},
		{
			MethodName: "UpdateMe",
			Handler:    _UserService_UpdateMe_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "acourse.proto",
}

// Client API for EmailService service

type EmailServiceClient interface {
	Send(ctx context.Context, in *Email, opts ...grpc.CallOption) (*Empty, error)
}

type emailServiceClient struct {
	cc *grpc.ClientConn
}

func NewEmailServiceClient(cc *grpc.ClientConn) EmailServiceClient {
	return &emailServiceClient{cc}
}

func (c *emailServiceClient) Send(ctx context.Context, in *Email, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := grpc.Invoke(ctx, "/acourse.EmailService/Send", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for EmailService service

type EmailServiceServer interface {
	Send(context.Context, *Email) (*Empty, error)
}

func RegisterEmailServiceServer(s *grpc.Server, srv EmailServiceServer) {
	s.RegisterService(&_EmailService_serviceDesc, srv)
}

func _EmailService_Send_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Email)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmailServiceServer).Send(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/acourse.EmailService/Send",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmailServiceServer).Send(ctx, req.(*Email))
	}
	return interceptor(ctx, in, info, handler)
}

var _EmailService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "acourse.EmailService",
	HandlerType: (*EmailServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Send",
			Handler:    _EmailService_Send_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "acourse.proto",
}

// Client API for PaymentService service

type PaymentServiceClient interface {
	ListWaitingPayments(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*PaymentsResponse, error)
	ListHistoryPayments(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*PaymentsResponse, error)
	ApprovePayments(ctx context.Context, in *PaymentIDsRequest, opts ...grpc.CallOption) (*Empty, error)
	RejectPayments(ctx context.Context, in *PaymentIDsRequest, opts ...grpc.CallOption) (*Empty, error)
	UpdatePrice(ctx context.Context, in *PaymentUpdatePriceRequest, opts ...grpc.CallOption) (*Empty, error)
}

type paymentServiceClient struct {
	cc *grpc.ClientConn
}

func NewPaymentServiceClient(cc *grpc.ClientConn) PaymentServiceClient {
	return &paymentServiceClient{cc}
}

func (c *paymentServiceClient) ListWaitingPayments(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*PaymentsResponse, error) {
	out := new(PaymentsResponse)
	err := grpc.Invoke(ctx, "/acourse.PaymentService/ListWaitingPayments", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentServiceClient) ListHistoryPayments(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*PaymentsResponse, error) {
	out := new(PaymentsResponse)
	err := grpc.Invoke(ctx, "/acourse.PaymentService/ListHistoryPayments", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentServiceClient) ApprovePayments(ctx context.Context, in *PaymentIDsRequest, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := grpc.Invoke(ctx, "/acourse.PaymentService/ApprovePayments", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentServiceClient) RejectPayments(ctx context.Context, in *PaymentIDsRequest, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := grpc.Invoke(ctx, "/acourse.PaymentService/RejectPayments", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentServiceClient) UpdatePrice(ctx context.Context, in *PaymentUpdatePriceRequest, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := grpc.Invoke(ctx, "/acourse.PaymentService/UpdatePrice", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for PaymentService service

type PaymentServiceServer interface {
	ListWaitingPayments(context.Context, *ListRequest) (*PaymentsResponse, error)
	ListHistoryPayments(context.Context, *ListRequest) (*PaymentsResponse, error)
	ApprovePayments(context.Context, *PaymentIDsRequest) (*Empty, error)
	RejectPayments(context.Context, *PaymentIDsRequest) (*Empty, error)
	UpdatePrice(context.Context, *PaymentUpdatePriceRequest) (*Empty, error)
}

func RegisterPaymentServiceServer(s *grpc.Server, srv PaymentServiceServer) {
	s.RegisterService(&_PaymentService_serviceDesc, srv)
}

func _PaymentService_ListWaitingPayments_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentServiceServer).ListWaitingPayments(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/acourse.PaymentService/ListWaitingPayments",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentServiceServer).ListWaitingPayments(ctx, req.(*ListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaymentService_ListHistoryPayments_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentServiceServer).ListHistoryPayments(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/acourse.PaymentService/ListHistoryPayments",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentServiceServer).ListHistoryPayments(ctx, req.(*ListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaymentService_ApprovePayments_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PaymentIDsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentServiceServer).ApprovePayments(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/acourse.PaymentService/ApprovePayments",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentServiceServer).ApprovePayments(ctx, req.(*PaymentIDsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaymentService_RejectPayments_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PaymentIDsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentServiceServer).RejectPayments(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/acourse.PaymentService/RejectPayments",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentServiceServer).RejectPayments(ctx, req.(*PaymentIDsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaymentService_UpdatePrice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PaymentUpdatePriceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentServiceServer).UpdatePrice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/acourse.PaymentService/UpdatePrice",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentServiceServer).UpdatePrice(ctx, req.(*PaymentUpdatePriceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _PaymentService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "acourse.PaymentService",
	HandlerType: (*PaymentServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListWaitingPayments",
			Handler:    _PaymentService_ListWaitingPayments_Handler,
		},
		{
			MethodName: "ListHistoryPayments",
			Handler:    _PaymentService_ListHistoryPayments_Handler,
		},
		{
			MethodName: "ApprovePayments",
			Handler:    _PaymentService_ApprovePayments_Handler,
		},
		{
			MethodName: "RejectPayments",
			Handler:    _PaymentService_RejectPayments_Handler,
		},
		{
			MethodName: "UpdatePrice",
			Handler:    _PaymentService_UpdatePrice_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "acourse.proto",
}

// Client API for CourseService service

type CourseServiceClient interface {
	ListCourses(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*CoursesResponse, error)
	ListPublicCourses(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*CoursesResponse, error)
	ListOwnCourses(ctx context.Context, in *UserIDRequest, opts ...grpc.CallOption) (*CoursesResponse, error)
	ListEnrolledCourses(ctx context.Context, in *UserIDRequest, opts ...grpc.CallOption) (*CoursesResponse, error)
	GetCourse(ctx context.Context, in *CourseIDRequest, opts ...grpc.CallOption) (*CourseResponse, error)
	CreateCourse(ctx context.Context, in *Course, opts ...grpc.CallOption) (*Course, error)
	UpdateCourse(ctx context.Context, in *Course, opts ...grpc.CallOption) (*Empty, error)
	EnrollCourse(ctx context.Context, in *EnrollRequest, opts ...grpc.CallOption) (*Empty, error)
	AttendCourse(ctx context.Context, in *CourseIDRequest, opts ...grpc.CallOption) (*Empty, error)
	OpenAttend(ctx context.Context, in *CourseIDRequest, opts ...grpc.CallOption) (*Empty, error)
	CloseAttend(ctx context.Context, in *CourseIDRequest, opts ...grpc.CallOption) (*Empty, error)
}

type courseServiceClient struct {
	cc *grpc.ClientConn
}

func NewCourseServiceClient(cc *grpc.ClientConn) CourseServiceClient {
	return &courseServiceClient{cc}
}

func (c *courseServiceClient) ListCourses(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*CoursesResponse, error) {
	out := new(CoursesResponse)
	err := grpc.Invoke(ctx, "/acourse.CourseService/ListCourses", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *courseServiceClient) ListPublicCourses(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*CoursesResponse, error) {
	out := new(CoursesResponse)
	err := grpc.Invoke(ctx, "/acourse.CourseService/ListPublicCourses", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *courseServiceClient) ListOwnCourses(ctx context.Context, in *UserIDRequest, opts ...grpc.CallOption) (*CoursesResponse, error) {
	out := new(CoursesResponse)
	err := grpc.Invoke(ctx, "/acourse.CourseService/ListOwnCourses", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *courseServiceClient) ListEnrolledCourses(ctx context.Context, in *UserIDRequest, opts ...grpc.CallOption) (*CoursesResponse, error) {
	out := new(CoursesResponse)
	err := grpc.Invoke(ctx, "/acourse.CourseService/ListEnrolledCourses", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *courseServiceClient) GetCourse(ctx context.Context, in *CourseIDRequest, opts ...grpc.CallOption) (*CourseResponse, error) {
	out := new(CourseResponse)
	err := grpc.Invoke(ctx, "/acourse.CourseService/GetCourse", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *courseServiceClient) CreateCourse(ctx context.Context, in *Course, opts ...grpc.CallOption) (*Course, error) {
	out := new(Course)
	err := grpc.Invoke(ctx, "/acourse.CourseService/CreateCourse", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *courseServiceClient) UpdateCourse(ctx context.Context, in *Course, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := grpc.Invoke(ctx, "/acourse.CourseService/UpdateCourse", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *courseServiceClient) EnrollCourse(ctx context.Context, in *EnrollRequest, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := grpc.Invoke(ctx, "/acourse.CourseService/EnrollCourse", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *courseServiceClient) AttendCourse(ctx context.Context, in *CourseIDRequest, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := grpc.Invoke(ctx, "/acourse.CourseService/AttendCourse", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *courseServiceClient) OpenAttend(ctx context.Context, in *CourseIDRequest, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := grpc.Invoke(ctx, "/acourse.CourseService/OpenAttend", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *courseServiceClient) CloseAttend(ctx context.Context, in *CourseIDRequest, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := grpc.Invoke(ctx, "/acourse.CourseService/CloseAttend", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for CourseService service

type CourseServiceServer interface {
	ListCourses(context.Context, *ListRequest) (*CoursesResponse, error)
	ListPublicCourses(context.Context, *ListRequest) (*CoursesResponse, error)
	ListOwnCourses(context.Context, *UserIDRequest) (*CoursesResponse, error)
	ListEnrolledCourses(context.Context, *UserIDRequest) (*CoursesResponse, error)
	GetCourse(context.Context, *CourseIDRequest) (*CourseResponse, error)
	CreateCourse(context.Context, *Course) (*Course, error)
	UpdateCourse(context.Context, *Course) (*Empty, error)
	EnrollCourse(context.Context, *EnrollRequest) (*Empty, error)
	AttendCourse(context.Context, *CourseIDRequest) (*Empty, error)
	OpenAttend(context.Context, *CourseIDRequest) (*Empty, error)
	CloseAttend(context.Context, *CourseIDRequest) (*Empty, error)
}

func RegisterCourseServiceServer(s *grpc.Server, srv CourseServiceServer) {
	s.RegisterService(&_CourseService_serviceDesc, srv)
}

func _CourseService_ListCourses_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CourseServiceServer).ListCourses(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/acourse.CourseService/ListCourses",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CourseServiceServer).ListCourses(ctx, req.(*ListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CourseService_ListPublicCourses_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CourseServiceServer).ListPublicCourses(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/acourse.CourseService/ListPublicCourses",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CourseServiceServer).ListPublicCourses(ctx, req.(*ListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CourseService_ListOwnCourses_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CourseServiceServer).ListOwnCourses(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/acourse.CourseService/ListOwnCourses",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CourseServiceServer).ListOwnCourses(ctx, req.(*UserIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CourseService_ListEnrolledCourses_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CourseServiceServer).ListEnrolledCourses(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/acourse.CourseService/ListEnrolledCourses",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CourseServiceServer).ListEnrolledCourses(ctx, req.(*UserIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CourseService_GetCourse_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CourseIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CourseServiceServer).GetCourse(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/acourse.CourseService/GetCourse",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CourseServiceServer).GetCourse(ctx, req.(*CourseIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CourseService_CreateCourse_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Course)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CourseServiceServer).CreateCourse(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/acourse.CourseService/CreateCourse",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CourseServiceServer).CreateCourse(ctx, req.(*Course))
	}
	return interceptor(ctx, in, info, handler)
}

func _CourseService_UpdateCourse_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Course)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CourseServiceServer).UpdateCourse(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/acourse.CourseService/UpdateCourse",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CourseServiceServer).UpdateCourse(ctx, req.(*Course))
	}
	return interceptor(ctx, in, info, handler)
}

func _CourseService_EnrollCourse_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EnrollRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CourseServiceServer).EnrollCourse(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/acourse.CourseService/EnrollCourse",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CourseServiceServer).EnrollCourse(ctx, req.(*EnrollRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CourseService_AttendCourse_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CourseIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CourseServiceServer).AttendCourse(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/acourse.CourseService/AttendCourse",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CourseServiceServer).AttendCourse(ctx, req.(*CourseIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CourseService_OpenAttend_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CourseIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CourseServiceServer).OpenAttend(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/acourse.CourseService/OpenAttend",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CourseServiceServer).OpenAttend(ctx, req.(*CourseIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CourseService_CloseAttend_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CourseIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CourseServiceServer).CloseAttend(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/acourse.CourseService/CloseAttend",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CourseServiceServer).CloseAttend(ctx, req.(*CourseIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _CourseService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "acourse.CourseService",
	HandlerType: (*CourseServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListCourses",
			Handler:    _CourseService_ListCourses_Handler,
		},
		{
			MethodName: "ListPublicCourses",
			Handler:    _CourseService_ListPublicCourses_Handler,
		},
		{
			MethodName: "ListOwnCourses",
			Handler:    _CourseService_ListOwnCourses_Handler,
		},
		{
			MethodName: "ListEnrolledCourses",
			Handler:    _CourseService_ListEnrolledCourses_Handler,
		},
		{
			MethodName: "GetCourse",
			Handler:    _CourseService_GetCourse_Handler,
		},
		{
			MethodName: "CreateCourse",
			Handler:    _CourseService_CreateCourse_Handler,
		},
		{
			MethodName: "UpdateCourse",
			Handler:    _CourseService_UpdateCourse_Handler,
		},
		{
			MethodName: "EnrollCourse",
			Handler:    _CourseService_EnrollCourse_Handler,
		},
		{
			MethodName: "AttendCourse",
			Handler:    _CourseService_AttendCourse_Handler,
		},
		{
			MethodName: "OpenAttend",
			Handler:    _CourseService_OpenAttend_Handler,
		},
		{
			MethodName: "CloseAttend",
			Handler:    _CourseService_CloseAttend_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "acourse.proto",
}

func init() { proto.RegisterFile("acourse.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 1408 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xbc, 0x58, 0xcd, 0x6e, 0x1c, 0xc5,
	0x13, 0xcf, 0x7e, 0xcf, 0xd6, 0x7a, 0xd7, 0x76, 0x27, 0xf2, 0x7f, 0x32, 0xff, 0x08, 0x85, 0x26,
	0x28, 0x51, 0x20, 0x16, 0x38, 0x02, 0x05, 0x88, 0x12, 0x2c, 0xdb, 0x4a, 0x0c, 0x89, 0x1c, 0x4d,
	0xb0, 0xe0, 0xc8, 0x78, 0xa7, 0xe3, 0x34, 0x1a, 0x4f, 0x0f, 0xd3, 0x3d, 0x8e, 0xf6, 0x1d, 0xb8,
	0x71, 0xe1, 0x0e, 0x57, 0xde, 0x80, 0x27, 0xe0, 0x39, 0x38, 0xf1, 0x14, 0xa8, 0xbf, 0xa6, 0x7b,
	0x67, 0xd7, 0x21, 0x89, 0x81, 0x93, 0xb7, 0xaa, 0xab, 0xaa, 0xab, 0x7e, 0xd5, 0x55, 0x53, 0x65,
	0x18, 0x27, 0x53, 0x56, 0x95, 0x9c, 0x6c, 0x16, 0x25, 0x13, 0x0c, 0x0d, 0x0c, 0x89, 0x6f, 0xc2,
	0xe4, 0x01, 0x11, 0x87, 0x9c, 0x94, 0x31, 0xf9, 0xbe, 0x22, 0x5c, 0xa0, 0x10, 0x06, 0x15, 0x27,
	0xe5, 0x7e, 0xca, 0xc3, 0xd6, 0xd5, 0xce, 0x8d, 0x61, 0x6c, 0x49, 0xfc, 0x31, 0xac, 0xd6, 0xb2,
	0xbc, 0x60, 0x39, 0x27, 0xe8, 0x1d, 0xe8, 0xc9, 0x53, 0x2d, 0x3a, 0xda, 0x1a, 0x6f, 0xda, 0x6b,
	0x94, 0x94, 0x3e, 0xc3, 0x87, 0x30, 0x7e, 0x40, 0xc4, 0x63, 0x52, 0x6b, 0xbd, 0x0d, 0x5d, 0x79,
	0x12, 0xb6, 0xae, 0xb6, 0x16, 0x95, 0xd4, 0x91, 0x14, 0x29, 0x59, 0x46, 0xc2, 0x76, 0x43, 0x24,
	0x66, 0x19, 0x89, 0xd5, 0x11, 0xfe, 0x0c, 0x46, 0x8f, 0x28, 0x17, 0xd6, 0xef, 0x0d, 0xe8, 0xb3,
	0x67, 0xcf, 0x38, 0x11, 0xca, 0x6c, 0x2f, 0x36, 0x14, 0xba, 0x04, 0xbd, 0x8c, 0x9e, 0x50, 0xa1,
	0x4c, 0xf5, 0x62, 0x4d, 0xe0, 0x9f, 0x5a, 0xb0, 0xf6, 0x24, 0x99, 0x9d, 0x90, 0x5c, 0xf0, 0xda,
	0xaf, 0xf7, 0x21, 0x28, 0x0c, 0xcf, 0x04, 0xb4, 0x56, 0x5f, 0x6c, 0x84, 0xe3, 0x5a, 0x02, 0x5d,
	0xb7, 0xb1, 0xb7, 0x95, 0xe8, 0xfa, 0x5c, 0x18, 0x5f, 0xd1, 0x7c, 0x66, 0xe2, 0x47, 0xb7, 0x60,
	0xa0, 0x4f, 0x78, 0xd8, 0x51, 0xa2, 0x17, 0x6b, 0xd1, 0x1d, 0xf5, 0x47, 0x09, 0x5b, 0x19, 0x7c,
	0x1b, 0xd6, 0xcd, 0x65, 0xfb, 0xbb, 0xdc, 0x46, 0xf7, 0x16, 0x80, 0xb9, 0xd8, 0x25, 0xc6, 0xe3,
	0xe0, 0x03, 0xb8, 0x6c, 0x94, 0x0e, 0x8b, 0x34, 0x11, 0xe4, 0x49, 0x49, 0xa7, 0xc4, 0x2a, 0x5f,
	0x81, 0x61, 0x2d, 0xaa, 0xd0, 0x19, 0xc6, 0x8e, 0x21, 0x01, 0x2a, 0xa4, 0xb4, 0x02, 0xa8, 0x15,
	0x6b, 0x02, 0xff, 0xd2, 0x82, 0x55, 0xed, 0x9d, 0xc3, 0x67, 0xd3, 0x05, 0xa2, 0xe1, 0xb9, 0xd4,
	0x08, 0xe4, 0xe9, 0x49, 0x92, 0x65, 0x75, 0x24, 0xaf, 0x8e, 0xd0, 0x1d, 0x58, 0x21, 0x79, 0xc9,
	0xb2, 0x6c, 0x87, 0x55, 0x12, 0xfc, 0x4e, 0xc3, 0xfa, 0x9e, 0x3b, 0x8c, 0xe7, 0x24, 0xf1, 0x75,
	0x18, 0x4b, 0x63, 0xfb, 0xbb, 0xde, 0x33, 0xd0, 0xef, 0xd5, 0x04, 0x6a, 0x28, 0x7c, 0xcb, 0x86,
	0xe3, 0x44, 0x23, 0x08, 0xb4, 0xfd, 0x5a, 0xb8, 0xa6, 0xf1, 0x31, 0x8c, 0xf5, 0xa5, 0xaf, 0x20,
	0x8c, 0xd6, 0xa0, 0x53, 0x95, 0x99, 0xc2, 0x6f, 0x18, 0xcb, 0x9f, 0x08, 0x41, 0x77, 0xca, 0x52,
	0x12, 0x76, 0x14, 0x4b, 0xfd, 0x76, 0x38, 0x77, 0x7d, 0x9c, 0x7f, 0x6f, 0xc1, 0x44, 0x3b, 0x56,
	0xc3, 0x7c, 0x1d, 0xfa, 0xda, 0xb4, 0x29, 0x90, 0xd5, 0x06, 0xca, 0xb1, 0x39, 0x46, 0xef, 0x9a,
	0x3a, 0xd2, 0x45, 0xb2, 0x04, 0x5e, 0x5d, 0x4b, 0x11, 0x04, 0x1a, 0x33, 0x92, 0x2a, 0x87, 0x82,
	0xb8, 0xa6, 0xa5, 0x53, 0xec, 0x45, 0x4e, 0x52, 0xe5, 0x54, 0x10, 0x6b, 0x42, 0x6a, 0x14, 0x55,
	0x39, 0x7d, 0x9e, 0x70, 0x12, 0xf6, 0xb4, 0x86, 0xa5, 0xe5, 0x59, 0x22, 0x04, 0xc9, 0x53, 0x92,
	0x86, 0x7d, 0x7d, 0x66, 0x69, 0x3c, 0x80, 0xde, 0xde, 0x49, 0x21, 0x66, 0xf8, 0x14, 0xba, 0xd2,
	0x09, 0x34, 0x81, 0x36, 0xb5, 0x78, 0xb5, 0xa9, 0x32, 0x2c, 0x5d, 0xca, 0x93, 0x13, 0x62, 0xe0,
	0xaa, 0x69, 0x89, 0x99, 0xe2, 0x1b, 0xcc, 0x14, 0x4f, 0x62, 0xf6, 0x9c, 0x09, 0xa6, 0xdc, 0x1b,
	0xc6, 0x9a, 0x90, 0x2d, 0x2a, 0x39, 0x62, 0x95, 0x78, 0xac, 0xbd, 0x1b, 0xc6, 0x96, 0xc4, 0xdf,
	0x42, 0x60, 0x83, 0xff, 0x77, 0xee, 0xc6, 0x77, 0xa1, 0x2b, 0x7b, 0x90, 0x3c, 0x4d, 0xd2, 0x13,
	0x9a, 0xab, 0x0b, 0x82, 0x58, 0x13, 0xb2, 0x4c, 0x69, 0xce, 0x45, 0x59, 0x4d, 0x05, 0xd3, 0x79,
	0x09, 0x62, 0x8f, 0x83, 0xbf, 0x94, 0x00, 0x25, 0x34, 0x93, 0xce, 0x09, 0x66, 0xea, 0xb8, 0xad,
	0x43, 0xe2, 0xd5, 0xd1, 0x77, 0x64, 0x2a, 0x8c, 0x6f, 0x96, 0x94, 0xae, 0x1d, 0xb1, 0x74, 0x66,
	0xbc, 0x50, 0xbf, 0xbf, 0xe8, 0x06, 0x9d, 0xb5, 0x2e, 0xfe, 0x79, 0x00, 0x7d, 0xfd, 0x22, 0x16,
	0x62, 0xbd, 0x02, 0xc3, 0x69, 0x49, 0x12, 0x41, 0xd2, 0x6d, 0x6b, 0xd0, 0x31, 0xe4, 0x69, 0xa5,
	0xba, 0x84, 0x3c, 0xd5, 0x21, 0x3b, 0x86, 0x8c, 0x4c, 0x50, 0x91, 0x11, 0x1b, 0xb7, 0x22, 0xd0,
	0x4d, 0x58, 0xe3, 0xcf, 0x59, 0x29, 0x76, 0x09, 0x9f, 0x96, 0xb4, 0x10, 0x94, 0xe5, 0x06, 0xfc,
	0x05, 0x3e, 0xba, 0x0a, 0xa3, 0xd4, 0x13, 0xeb, 0x2b, 0x31, 0x9f, 0xe5, 0xb0, 0x1d, 0xf8, 0x79,
	0x35, 0x8f, 0xb1, 0x0c, 0x03, 0xcd, 0x55, 0x84, 0xe4, 0x72, 0x91, 0x94, 0x22, 0x1c, 0x6a, 0xae,
	0x22, 0x6c, 0xcd, 0xc1, 0x5c, 0xcd, 0x89, 0x59, 0x41, 0xc2, 0x91, 0x06, 0x4a, 0xfe, 0x96, 0xba,
	0xa7, 0x34, 0x25, 0x2c, 0x5c, 0xd1, 0xba, 0x8a, 0x70, 0x95, 0x38, 0xf6, 0x2a, 0x11, 0xdd, 0x80,
	0xd5, 0x94, 0xf2, 0xa9, 0xec, 0x2b, 0x24, 0x55, 0xfd, 0x33, 0x9c, 0xa8, 0xf3, 0x26, 0x1b, 0x7d,
	0x00, 0x03, 0xa6, 0xe2, 0xe0, 0xe1, 0xaa, 0x2a, 0xbd, 0x8d, 0x46, 0x85, 0x6e, 0x1e, 0xa8, 0xe3,
	0xd8, 0x8a, 0xa1, 0xdb, 0xb2, 0x7b, 0xe4, 0x42, 0x7d, 0x59, 0xd6, 0x54, 0x73, 0xfb, 0x5f, 0x53,
	0x65, 0x47, 0x9f, 0xc7, 0xb5, 0x20, 0xc2, 0xb6, 0x2b, 0xee, 0x12, 0x91, 0xd0, 0x2c, 0x5c, 0x57,
	0x31, 0xcc, 0xf1, 0xd0, 0x5d, 0x18, 0x25, 0x9c, 0xd3, 0xe3, 0x5c, 0x7f, 0xb5, 0x90, 0xb2, 0x1d,
	0x35, 0x6d, 0x6f, 0xd7, 0x22, 0xb1, 0x2f, 0x1e, 0xcd, 0x60, 0x60, 0xae, 0x75, 0x59, 0x6f, 0xf9,
	0x59, 0x6f, 0x64, 0xb2, 0xbd, 0x34, 0x93, 0x1a, 0xe1, 0x8e, 0x8f, 0xb0, 0xd4, 0x63, 0x2f, 0xf2,
	0x8c, 0x25, 0xe9, 0x61, 0xfc, 0xc8, 0xbc, 0x24, 0x9f, 0x15, 0xfd, 0xd0, 0x82, 0xbe, 0x46, 0x49,
	0xb6, 0xec, 0xa2, 0x3a, 0xca, 0xe8, 0xd4, 0xd4, 0x92, 0xa1, 0x24, 0x5f, 0xc7, 0x6a, 0x0a, 0xc9,
	0x50, 0x92, 0xaf, 0x3b, 0x8e, 0xe9, 0x66, 0x86, 0x92, 0xc5, 0xe7, 0x82, 0x33, 0x0d, 0xcd, 0xe3,
	0xc8, 0x06, 0x60, 0x33, 0x69, 0xbb, 0x9a, 0xa5, 0xa3, 0x6f, 0x00, 0x1c, 0x48, 0x6f, 0x0c, 0x06,
	0x82, 0x2e, 0x2b, 0x48, 0x6e, 0xfc, 0x52, 0xbf, 0xf1, 0x1f, 0x6d, 0x18, 0x79, 0x5f, 0xc7, 0x85,
	0x52, 0x3d, 0x7f, 0xb9, 0xfd, 0x87, 0xc5, 0x74, 0xae, 0xb2, 0xf9, 0xa8, 0x59, 0x36, 0xff, 0x5f,
	0x36, 0x3e, 0x34, 0x6b, 0x27, 0xba, 0x56, 0x3f, 0x94, 0x97, 0x24, 0x10, 0x6f, 0x01, 0xb8, 0x61,
	0xea, 0x6c, 0x90, 0xdb, 0x1e, 0xc8, 0xf8, 0xc7, 0x36, 0x0c, 0xcc, 0xd4, 0xf4, 0x8f, 0x76, 0x50,
	0x37, 0x83, 0x74, 0xfd, 0x19, 0x64, 0x6e, 0x86, 0xe8, 0x35, 0x66, 0x88, 0x6b, 0x30, 0x66, 0x25,
	0x3d, 0xa6, 0x79, 0x92, 0x69, 0x10, 0xfb, 0x0a, 0xc4, 0x79, 0xa6, 0x4b, 0xc1, 0xc0, 0x4f, 0x81,
	0x9d, 0x36, 0x02, 0x6f, 0xda, 0x30, 0x29, 0x1d, 0xba, 0x94, 0x6e, 0x40, 0x9f, 0x8b, 0x44, 0x54,
	0xdc, 0xe4, 0xd9, 0x50, 0x32, 0xf2, 0x44, 0x98, 0x44, 0xb7, 0x13, 0x81, 0xef, 0xc3, 0xc8, 0x9b,
	0xb7, 0x5e, 0x3a, 0xf8, 0x5c, 0x82, 0x9e, 0xce, 0x86, 0x99, 0xad, 0x15, 0xb1, 0xf5, 0x6b, 0x0b,
	0x46, 0xf2, 0x2b, 0xfc, 0x94, 0x94, 0xa7, 0xd2, 0xbd, 0x7b, 0x30, 0x30, 0x7b, 0x03, 0x72, 0x5d,
	0x6f, 0x7e, 0xeb, 0x88, 0xc2, 0xc5, 0x03, 0x3d, 0x0d, 0xe1, 0x0b, 0xe8, 0x43, 0xe8, 0xa9, 0xfd,
	0x01, 0x4d, 0xdc, 0x40, 0x28, 0xa7, 0x8c, 0x68, 0xc3, 0x57, 0x72, 0xfb, 0x05, 0xbe, 0x80, 0xde,
	0x83, 0x40, 0xcf, 0xc1, 0x8f, 0x09, 0x9a, 0xdf, 0x2f, 0xa2, 0x86, 0x11, 0x7c, 0x61, 0xeb, 0x0e,
	0xac, 0xa8, 0x8f, 0xb2, 0xf5, 0xf7, 0x06, 0x74, 0x9f, 0xca, 0x7e, 0xe2, 0x4b, 0x26, 0x34, 0x5b,
	0xa2, 0xf9, 0x67, 0x1b, 0x26, 0xe6, 0x01, 0x59, 0xe5, 0x87, 0x70, 0x51, 0x6e, 0x25, 0x5f, 0x27,
	0x54, 0xd0, 0xfc, 0xd8, 0xae, 0x18, 0xc8, 0xcd, 0xb2, 0xde, 0xce, 0x12, 0x5d, 0x6e, 0xae, 0x17,
	0xdc, 0x8b, 0xc1, 0x58, 0x7a, 0x48, 0xb9, 0x60, 0xe5, 0xec, 0x3c, 0x96, 0xee, 0xc3, 0xea, 0x76,
	0x51, 0x94, 0xec, 0x94, 0xd4, 0x56, 0xa2, 0xa6, 0xbc, 0xdb, 0x35, 0x16, 0xe3, 0x44, 0xf7, 0x60,
	0x12, 0x13, 0x39, 0x8d, 0xbc, 0xa1, 0xfe, 0x0e, 0x8c, 0xbc, 0xb5, 0x04, 0xe1, 0xa6, 0xf2, 0xe2,
	0xce, 0xb2, 0x04, 0xec, 0xdf, 0x7a, 0x30, 0x36, 0x7d, 0xc2, 0x60, 0x7d, 0x5f, 0x6f, 0x80, 0x66,
	0x4d, 0x39, 0x03, 0x99, 0xb0, 0xd1, 0x64, 0x7c, 0x60, 0xf6, 0x60, 0x5d, 0x8a, 0x3e, 0x51, 0xdf,
	0x9b, 0x37, 0x37, 0xb3, 0x0b, 0x13, 0x29, 0x7a, 0xf0, 0x22, 0xb7, 0x36, 0x36, 0xe6, 0xde, 0x5c,
	0xbd, 0x72, 0xbc, 0xd4, 0xca, 0xbe, 0xce, 0xf7, 0x9e, 0x19, 0xcd, 0xcf, 0x63, 0xea, 0x73, 0x18,
	0x3e, 0x20, 0x06, 0x17, 0xd4, 0x14, 0x74, 0x26, 0x9a, 0x33, 0x88, 0x67, 0x61, 0x0b, 0x56, 0x76,
	0x54, 0xb7, 0x33, 0x46, 0x9a, 0x3b, 0x48, 0xd4, 0x64, 0xa8, 0x3a, 0x5d, 0xd1, 0x89, 0x3c, 0x4b,
	0x67, 0xf1, 0x61, 0xc8, 0xd2, 0xb3, 0xbd, 0x46, 0xaa, 0x6c, 0x34, 0x56, 0xbe, 0xb3, 0x9f, 0xd4,
	0xa7, 0xb0, 0xb2, 0xad, 0x3e, 0xfb, 0x7f, 0x1b, 0xe5, 0xb2, 0x5b, 0xe1, 0xa0, 0x20, 0xb9, 0xd6,
	0x7f, 0x2d, 0xcd, 0x4f, 0x60, 0xb4, 0x93, 0x31, 0x4e, 0x5e, 0x5f, 0xf5, 0xa8, 0xaf, 0xfe, 0xf3,
	0x72, 0xfb, 0xaf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x72, 0x0c, 0x22, 0x1d, 0x8a, 0x11, 0x00, 0x00,
}
