// Code generated by protoc-gen-go.
// source: acourse.proto
// DO NOT EDIT!

/*
Package acourse is a generated protocol buffer package.

It is generated from these files:
	acourse.proto

It has these top-level messages:
	GetUserRequest
	GetUserResponse
	GetMeResponse
	Empty
	User
	Role
*/
package acourse

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type GetUserRequest struct {
	UserIds []string `protobuf:"bytes,1,rep,name=userIds" json:"userIds,omitempty"`
}

func (m *GetUserRequest) Reset()                    { *m = GetUserRequest{} }
func (m *GetUserRequest) String() string            { return proto.CompactTextString(m) }
func (*GetUserRequest) ProtoMessage()               {}
func (*GetUserRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *GetUserRequest) GetUserIds() []string {
	if m != nil {
		return m.UserIds
	}
	return nil
}

type GetUserResponse struct {
	Users []*User `protobuf:"bytes,1,rep,name=users" json:"users,omitempty"`
}

func (m *GetUserResponse) Reset()                    { *m = GetUserResponse{} }
func (m *GetUserResponse) String() string            { return proto.CompactTextString(m) }
func (*GetUserResponse) ProtoMessage()               {}
func (*GetUserResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *GetUserResponse) GetUsers() []*User {
	if m != nil {
		return m.Users
	}
	return nil
}

type GetMeResponse struct {
	User *User `protobuf:"bytes,1,opt,name=user" json:"user,omitempty"`
	Role *Role `protobuf:"bytes,2,opt,name=role" json:"role,omitempty"`
}

func (m *GetMeResponse) Reset()                    { *m = GetMeResponse{} }
func (m *GetMeResponse) String() string            { return proto.CompactTextString(m) }
func (*GetMeResponse) ProtoMessage()               {}
func (*GetMeResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *GetMeResponse) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *GetMeResponse) GetRole() *Role {
	if m != nil {
		return m.Role
	}
	return nil
}

type Empty struct {
}

func (m *Empty) Reset()                    { *m = Empty{} }
func (m *Empty) String() string            { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()               {}
func (*Empty) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

type User struct {
	Id       string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Username string `protobuf:"bytes,2,opt,name=username" json:"username,omitempty"`
	Name     string `protobuf:"bytes,3,opt,name=name" json:"name,omitempty"`
	Photo    string `protobuf:"bytes,4,opt,name=photo" json:"photo,omitempty"`
	AboutMe  string `protobuf:"bytes,5,opt,name=aboutMe" json:"aboutMe,omitempty"`
}

func (m *User) Reset()                    { *m = User{} }
func (m *User) String() string            { return proto.CompactTextString(m) }
func (*User) ProtoMessage()               {}
func (*User) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *User) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *User) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *User) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *User) GetPhoto() string {
	if m != nil {
		return m.Photo
	}
	return ""
}

func (m *User) GetAboutMe() string {
	if m != nil {
		return m.AboutMe
	}
	return ""
}

type Role struct {
	Admin      bool `protobuf:"varint,1,opt,name=admin" json:"admin,omitempty"`
	Instructor bool `protobuf:"varint,2,opt,name=instructor" json:"instructor,omitempty"`
}

func (m *Role) Reset()                    { *m = Role{} }
func (m *Role) String() string            { return proto.CompactTextString(m) }
func (*Role) ProtoMessage()               {}
func (*Role) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *Role) GetAdmin() bool {
	if m != nil {
		return m.Admin
	}
	return false
}

func (m *Role) GetInstructor() bool {
	if m != nil {
		return m.Instructor
	}
	return false
}

func init() {
	proto.RegisterType((*GetUserRequest)(nil), "acourse.GetUserRequest")
	proto.RegisterType((*GetUserResponse)(nil), "acourse.GetUserResponse")
	proto.RegisterType((*GetMeResponse)(nil), "acourse.GetMeResponse")
	proto.RegisterType((*Empty)(nil), "acourse.Empty")
	proto.RegisterType((*User)(nil), "acourse.User")
	proto.RegisterType((*Role)(nil), "acourse.Role")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for UserService service

type UserServiceClient interface {
	GetUser(ctx context.Context, in *GetUserRequest, opts ...grpc.CallOption) (*GetUserResponse, error)
	GetMe(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*GetMeResponse, error)
	UpdateMe(ctx context.Context, in *User, opts ...grpc.CallOption) (*Empty, error)
}

type userServiceClient struct {
	cc *grpc.ClientConn
}

func NewUserServiceClient(cc *grpc.ClientConn) UserServiceClient {
	return &userServiceClient{cc}
}

func (c *userServiceClient) GetUser(ctx context.Context, in *GetUserRequest, opts ...grpc.CallOption) (*GetUserResponse, error) {
	out := new(GetUserResponse)
	err := grpc.Invoke(ctx, "/acourse.UserService/GetUser", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) GetMe(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*GetMeResponse, error) {
	out := new(GetMeResponse)
	err := grpc.Invoke(ctx, "/acourse.UserService/GetMe", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) UpdateMe(ctx context.Context, in *User, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := grpc.Invoke(ctx, "/acourse.UserService/UpdateMe", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for UserService service

type UserServiceServer interface {
	GetUser(context.Context, *GetUserRequest) (*GetUserResponse, error)
	GetMe(context.Context, *Empty) (*GetMeResponse, error)
	UpdateMe(context.Context, *User) (*Empty, error)
}

func RegisterUserServiceServer(s *grpc.Server, srv UserServiceServer) {
	s.RegisterService(&_UserService_serviceDesc, srv)
}

func _UserService_GetUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).GetUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/acourse.UserService/GetUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).GetUser(ctx, req.(*GetUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_GetMe_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).GetMe(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/acourse.UserService/GetMe",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).GetMe(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_UpdateMe_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(User)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).UpdateMe(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/acourse.UserService/UpdateMe",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).UpdateMe(ctx, req.(*User))
	}
	return interceptor(ctx, in, info, handler)
}

var _UserService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "acourse.UserService",
	HandlerType: (*UserServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetUser",
			Handler:    _UserService_GetUser_Handler,
		},
		{
			MethodName: "GetMe",
			Handler:    _UserService_GetMe_Handler,
		},
		{
			MethodName: "UpdateMe",
			Handler:    _UserService_UpdateMe_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "acourse.proto",
}

func init() { proto.RegisterFile("acourse.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 330 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x64, 0x52, 0x4d, 0x4b, 0xf3, 0x40,
	0x10, 0x6e, 0xda, 0xe4, 0x4d, 0x3a, 0xa5, 0x7d, 0x61, 0x10, 0x5d, 0x72, 0x90, 0xba, 0x5e, 0x44,
	0xa1, 0x60, 0x05, 0x4f, 0xe2, 0x4d, 0x8a, 0x87, 0x5e, 0x56, 0xfa, 0x03, 0xd2, 0x66, 0xc0, 0x40,
	0x9b, 0x8d, 0xbb, 0x9b, 0x82, 0x3f, 0xca, 0xff, 0x28, 0x3b, 0x69, 0x63, 0x3f, 0x6e, 0x7d, 0xbe,
	0x66, 0xb6, 0xcf, 0x04, 0x86, 0xd9, 0x4a, 0xd7, 0xc6, 0xd2, 0xa4, 0x32, 0xda, 0x69, 0x8c, 0x77,
	0x50, 0xde, 0xc3, 0x68, 0x46, 0x6e, 0x61, 0xc9, 0x28, 0xfa, 0xaa, 0xc9, 0x3a, 0x14, 0x10, 0xd7,
	0x96, 0xcc, 0x7b, 0x6e, 0x45, 0x30, 0xee, 0xdd, 0xf5, 0xd5, 0x1e, 0xca, 0x67, 0xf8, 0xdf, 0x7a,
	0x6d, 0xa5, 0x4b, 0x4b, 0x78, 0x0b, 0x91, 0x57, 0x1b, 0xeb, 0x60, 0x3a, 0x9c, 0xec, 0xd7, 0xb0,
	0xab, 0xd1, 0xe4, 0x02, 0x86, 0x33, 0x72, 0x73, 0x6a, 0x53, 0x37, 0x10, 0x7a, 0x45, 0x04, 0xe3,
	0xe0, 0x3c, 0xc4, 0x92, 0xb7, 0x18, 0xbd, 0x26, 0xd1, 0x3d, 0xb1, 0x28, 0xbd, 0x26, 0xc5, 0x92,
	0x8c, 0x21, 0x7a, 0xdb, 0x54, 0xee, 0x5b, 0x6e, 0x21, 0xf4, 0x49, 0x1c, 0x41, 0xb7, 0xc8, 0x79,
	0x68, 0x5f, 0x75, 0x8b, 0x1c, 0x53, 0x48, 0xfc, 0xac, 0x32, 0xdb, 0x34, 0x73, 0xfa, 0xaa, 0xc5,
	0x88, 0x10, 0x32, 0xdf, 0x63, 0x9e, 0x7f, 0xe3, 0x05, 0x44, 0xd5, 0xa7, 0x76, 0x5a, 0x84, 0x4c,
	0x36, 0xc0, 0xf7, 0x91, 0x2d, 0x75, 0xed, 0xe6, 0x24, 0x22, 0xe6, 0xf7, 0x50, 0xbe, 0x40, 0xe8,
	0x9f, 0xe3, 0x73, 0x59, 0xbe, 0x29, 0x4a, 0x5e, 0x9d, 0xa8, 0x06, 0xe0, 0x35, 0x40, 0x51, 0x5a,
	0x67, 0xea, 0x95, 0xd3, 0x86, 0xf7, 0x27, 0xea, 0x80, 0x99, 0xfe, 0x04, 0x30, 0xf0, 0xcf, 0xfe,
	0x20, 0xb3, 0x2d, 0x56, 0x84, 0xaf, 0x10, 0xef, 0xda, 0xc5, 0xab, 0xf6, 0xef, 0x1e, 0xdf, 0x26,
	0x15, 0xe7, 0x42, 0x53, 0xa9, 0xec, 0xe0, 0x23, 0x44, 0xdc, 0x32, 0x8e, 0x5a, 0x13, 0xd7, 0x93,
	0x5e, 0x1e, 0x86, 0xfe, 0xae, 0x20, 0x3b, 0xf8, 0x00, 0xc9, 0xa2, 0xca, 0x33, 0x47, 0x73, 0xc2,
	0xe3, 0x2b, 0xa4, 0x27, 0x43, 0x64, 0x67, 0xf9, 0x8f, 0xbf, 0x9c, 0xa7, 0xdf, 0x00, 0x00, 0x00,
	0xff, 0xff, 0x85, 0x70, 0x33, 0x9f, 0x4a, 0x02, 0x00, 0x00,
}
