steps:
- name: gcr.io/cloud-builders/kubectl
  args: [set, image, -n, $_NAMESPACE, deploy/$_DEPLOYMENT, acourse=gcr.io/$PROJECT_ID/acourse:$COMMIT_SHA]
  env:
  - CLOUDSDK_COMPUTE_ZONE=$_CLOUDSDK_COMPUTE_ZONE
  - CLOUDSDK_CONTAINER_CLUSTER=$_CLOUDSDK_CONTAINER_CLUSTER
