steps:
- name: golang:1.12.3
  args: [go, build, -o, acourse, -ldflags, -w -s, main.go]
  env:
  - GOOS=linux
  - GOARCH=amd64
  - CGO_ENABLED=0
  - GOPROXY=https://gomodprox.com

- name: node:10.15.3
  entrypoint: yarn
  args: [install]
  id: yarn-install
  waitFor: ['-']
- name: node:10.15.3
  entrypoint: yarn
  args: [run, gulp]
  waitFor: [yarn-install]
  env:
  - NODE_ENV=production

- name: gcr.io/cloud-builders/docker
  args: [build, -t, gcr.io/$PROJECT_ID/acourse:$COMMIT_SHA, '.']
- name: gcr.io/cloud-builders/docker
  args: [push, gcr.io/$PROJECT_ID/acourse:$COMMIT_SHA]

- name: acoshift/kubectl
  args: [set, image, $_RESOURCE, acourse=gcr.io/$PROJECT_ID/acourse:$COMMIT_SHA]
  env:
  - SERVER=$_SERVER
  - NAMESPACE=$_NAMESPACE
  secretEnv:
  - TOKEN

images:
- gcr.io/$PROJECT_ID/acourse:$COMMIT_SHA

secrets:
- kmsKeyName: projects/acourse-d9d0a/locations/global/keyRings/builder/cryptoKeys/key
  secretEnv:
    TOKEN: CiQAKWs1nzr6FeNR6GQlTQ+cjv28BJRWiocGcV25ByajDojmuVUS8AYA2nfHuv+NwPv1L0ahbgRdvh6LhOrbM8u9/SAHXyDxHuXdgYYOVcFAId/GC4QvhgSba14/K9YEziX+i+9kuR7jsJsC/XNLiQAy45rPr//ccgr+EjPpvuNJS1iOKedEC1qdMzBwOo4zD6WW7u3mkKd3pCPcv0GgUFTCTAcO9Xy96NzURZ2hSvLMr1KQu9jpjZVgXhXYuRvpQNGbRm5mxClrULZTSRGOEuWYtESmrJ9rfS4euHvnurO/z6UvP4fX3eOGm6YqN9qNOatPUCYtjIra0UTouHSxC1Sakav8ih9htUdzev3N8U0AACu/2yIAqiZ+BbGMsQpHl5thQKXEH+Jpjj46vm5pQde19Zy1dhyQtXk72V18M0sljPp16UTrx0IT15Bhfqrvn9NYeW6iJ+Hj+UEAhiGCH3rGYl+58UJ3+wz5lk+6QeB5VBqd3PAiCZGHGL4h//YaWn07SAl/ghIKj9HKZ/2zkGRBzaLnyjBvEFU0j9Wtk2GMC4u4GnoggeAO+ff9AHpe1afe+osHmSc1RIP/1fCwNxLWerrGIUaia99d5MAKr2jww0JdlSoW2PR0AyM0tq6RbFvfxh4+TvusbPpdFviody+qn7FdftZLGhxYb+GM9yZKBgcopHA9YRbHWrMYVGGCQ3jyiWwl+DVx/UNPpMp0BBjoCjuurREGKRRc3nqaUbN4PlWS3e872FAOzJpwstgjVoTMKAXmnEbFDdmUifvcqNtInMYvQm08/34V/QpTHMEqqcM34URvh/Wi9nM5EgGWNjrvmXBv9EuzfuTQjahFTDdakjlhTBSKFArSuE4vAjrThsaLcSPA2mjSuS7C6Ozbzbc1oa7FO2Xd32481ensZLeqbBD+IHghw6k2i+EydOVT57Ubv++74CbmFLL7tMK3/IF/RRB6IwX/cMP9csLNoJ42o/ClPJ+mbQw/ELRc5XouaQBORZBa0OmMow+QCZNQJKexckVpcQ2XjwFlZgto7TNmGHO4V8iakxTfcdA22RrRO83JIVy6R9BXwmdYs6X6c3QlphmT3VeYVf8jloZyUKPSLIT3DSQX6NI1aNX9a/PfM0aZqxry7iay4UyMLbsUsyP7iNyTyDJdBkKPauslWEa8zdWilxps9x9N5P6z1c7ff8mrvtXnueSIsB1EwqqKCjZDALmCmvxH
