steps:
- name: golang:1.12.7
  args: [go, build, -o, acourse, -ldflags, -w -s, main.go]
  env:
  - GOOS=linux
  - GOARCH=amd64
  - CGO_ENABLED=0
  - GOPROXY=https://proxy.golang.org

- name: node:10.16.0
  entrypoint: yarn
  args: [install]
  id: yarn-install
  waitFor: ['-']
- name: node:10.16.0
  entrypoint: yarn
  args: [run, gulp]
  waitFor: [yarn-install]
  env:
  - NODE_ENV=production

- name: gcr.io/cloud-builders/docker
  args: [build, -t, gcr.io/$PROJECT_ID/acourse:$COMMIT_SHA, '.']
- name: gcr.io/cloud-builders/docker
  args: [push, gcr.io/$PROJECT_ID/acourse:$COMMIT_SHA]

- name: acoshift/kubectl
  args: [set, image, $_RESOURCE, app=gcr.io/$PROJECT_ID/acourse:$COMMIT_SHA]
  env:
  - SERVER=$_SERVER
  - NAMESPACE=$_NAMESPACE
  - TOKEN=$_TOKEN

images:
- gcr.io/$PROJECT_ID/acourse:$COMMIT_SHA

