steps:
- name: golang:1.14.3
  args: [go, build, -o, acourse, -ldflags, -w -s, main.go]

- name: node:10.16.3
  entrypoint: yarn
  args: [install]
  id: yarn-install
  waitFor: ['-']
- name: node:10.16.3
  entrypoint: yarn
  args: [run, gulp]
  waitFor: [yarn-install]

- name: gcr.io/cloud-builders/docker
  args: [build, -t, gcr.io/$PROJECT_ID/acourse:$COMMIT_SHA, '.']
- name: gcr.io/cloud-builders/docker
  args: [push, gcr.io/$PROJECT_ID/acourse:$COMMIT_SHA]

- name: gcr.io/deploys-app/cli
  args: [deployment, set, image, acourse, -project=acourse, -image=gcr.io/$PROJECT_ID/acourse:$COMMIT_SHA]

options:
  env:
  - CGO_ENABLED=0
  - NODE_ENV=production

images:
- gcr.io/$PROJECT_ID/acourse:$COMMIT_SHA
