name: Deploy
on:
  push:
    branches:
    - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: docker/login-action@v1
      with:
        registry: registry.deploys.app
        username: ${{ secrets.DEPLOYS_AUTH_USER }}
        password: ${{ secrets.DEPLOYS_AUTH_PASS }}
    - uses: docker/setup-buildx-action@v2
    - id: docker_build
      uses: docker/build-push-action@v4
      with:
        push: true
        provenance: false
        tags: registry.deploys.app/acourse/acourse
    - uses: deploys-app/deploys-action@v1.0.5
      with:
        project: acourse
        location: gke.cluster-rcf2
        name: acourse
        image: registry.deploys.app/acourse/acourse@${{ steps.docker_build.outputs.digest }}
        minReplicas: 1
        maxReplicas: 1
      env:
        DEPLOYS_AUTH_USER: ${{ secrets.DEPLOYS_AUTH_USER }}
        DEPLOYS_AUTH_PASS: ${{ secrets.DEPLOYS_AUTH_PASS }}
